#!/bin/bash

# add
git add .

# check if a commit message is provided as an argument
if [ -z "$1" ]; then
    read -p "Enter commit message: " message
else
    shift
    message="$@"
fi

# commit the changes with the commit message
git commit -m "$message"

# push the changes
git push
